#!/bin/sh /etc/rc.common

#Copyright (c) 2021-2022 Qualcomm Technologies, Inc
#All Rights Reserved.
#Confidential and Proprietary - Qualcomm Technologies, Inc

START=03
STOP=90


USE_PROCD=1

start_service() {
        procd_open_instance
 		procd_set_param command /usr/bin/selinux-labeldev.sh
 		procd_close_instance
}

stop_service() {
         echo "Stopping --dummy call"
         # commands to kill application
}
