#!/bin/sh /etc/rc.common

# Copyright (c) 2022 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear


START=03
STOP=90


USE_PROCD=1

start_service() {
        procd_open_instance
 		procd_set_param command /usr/bin/selinux-labeldev.sh
 		procd_close_instance
}

stop_service() {
         echo "Stopping --dummy call"
         # commands to kill application
}
